In [9]:
using LinearAlgebra

A =[1 4 -1 4; 2 2 2 3; 3 -1 6 2; 4 0 5 3]

4×4 Matrix{Int64}:
 1   4  -1  4
 2   2   2  3
 3  -1   6  2
 4   0   5  3

In [8]:
det(A)

-9.000000000000004

In [13]:
B=zeros(6,6);
B[1,6]=1;
B[2,5]=-2;
B[3,4]=4;
B[4,3]=3;
B[5,2]=5;
B[6,1]=1/6;
B

6×6 Matrix{Float64}:
 0.0       0.0  0.0  0.0   0.0  1.0
 0.0       0.0  0.0  0.0  -2.0  0.0
 0.0       0.0  0.0  4.0   0.0  0.0
 0.0       0.0  3.0  0.0   0.0  0.0
 0.0       5.0  0.0  0.0   0.0  0.0
 0.166667  0.0  0.0  0.0   0.0  0.0

In [15]:
det(B)

20.0

In [21]:
C=ones(4,4).*2+Diagonal([1,1,1,1]);
C

4×4 Matrix{Float64}:
 3.0  2.0  2.0  2.0
 2.0  3.0  2.0  2.0
 2.0  2.0  3.0  2.0
 2.0  2.0  2.0  3.0

In [22]:
det(C)

9.000000000000002

## 首先，我们这里是一个 markdown
- 我们要在这里
- 做自 
公式试试 $ \frac{a}{b} + \cos(x)$

In [14]:
pwd()

"/home/huchq/Documents/project/julia_learing/notebook"